import Footer from './components/utils/Footer'
import Navbar from './components/utils/Navbar'
import { AppDataProvider } from './context/Appdata'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppDataProvider>
        <Navbar />
          {children}
        </AppDataProvider>
        <Footer/>
        </body>
    </html>
  )
}
